import '@coinbase/onchainkit/styles.css';
import './globals.css';

import type { Metadata } from 'next';
export async function generateMetadata(): Promise<Metadata> {
  const URL = process.env.NEXT_PUBLIC_URL as string;
  return {
    title: "FundUC", //process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
    description: 'Generated by `create-onchain --mini`',
    other: {
      'fc:frame': JSON.stringify({
        version: 'next',
        imageUrl: process.env.NEXT_PUBLIC_APP_HERO_IMAGE,
        button: {
          title: `Launch ${process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME}`,
          action: {
            type: 'launch_frame',
            name: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
            url: URL,
            splashImageUrl: process.env.NEXT_PUBLIC_SPLASH_IMAGE,
            splashBackgroundColor: process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR,
          },
        },
      }),
    },
  };
}


import { MiniKitContextProvider } from '@/providers/MiniKitProvider';
import { CurrencyProvider } from './contexts/CurrencyContext';
import { Web3Provider } from './contexts/Web3Context';
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      {/* <head>

      </head> */}
      <body>
        <MiniKitContextProvider>
          <Web3Provider>
            <CurrencyProvider>
              {children}
            </CurrencyProvider>
          </Web3Provider>
        </MiniKitContextProvider>
      </body>
    </html>
  );
}